os:
  - osx
language: generic
osx_image: xcode8
script:
  - xcodebuild -scheme TABResourceLoader -configuration Debug -sdk iphonesimulator10.0 -destination "OS=10.0,name=iPhone 6s" test -enableCodeCoverage YES
after_success:
  - bash <(curl -s https://codecov.io/bash)