os:
  - osx
language: generic
osx_image: xcode8
script:
  - xcodebuild -scheme TABResourceLoader -configuration Debug -sdk iphonesimulator9.3 -destination "OS=9.3,name=iPad 2" test -enableCodeCoverage YES
after_success:
  - bash <(curl -s https://codecov.io/bash)